### ISSUE TITLE
handler から fields にアクセスしたい

### ISSUE THREAD

**Issue by melpon** [yamionp/spreadsheetconverter#3]
handler はフォーマット出力を行う関係上、`Config.rules['fields']` のデータにアクセスする可能性が高いです。
なので handler からアクセスできるようにして欲しいです。

一応、以下のように書くことで handler 内で fields を使えました。

``` yaml
fields: &fields
- column: ID
  name: 連番
  type: int
...
handler:
  type: test
  ...
  fields: *fields
```

が、fields の利用頻度は高いと思われるので、使えるようにして欲しいです。
（あるいは `Config` や `Config.rules` を直接使えるようなっててもいいです）
